import { TipCategory } from "./tips.const";

export const tipCategories: TipCategory[] = [
  {
    category: "Food service",
    label: "Fast food",
    unit: "percentage",
    items: [
      {
        rating: "🙂",
        value: 10,
        ratingText: "Good",
        isRecommendedAmount: false,
      },
      {
        rating: "😊",
        value: 12,
        ratingText: "Great",
        isRecommendedAmount: true,
      },
      {
        rating: "🤩",
        value: 15,
        ratingText: "Excellent",
        isRecommendedAmount: false,
      },
    ],
    id: 1,
    transKey: "fast-food",
  },
  {
    category: "Food service",
    label: "Sit-down restaurant",
    unit: "percentage",
    items: [
      {
        rating: "🙂",
        value: 15,
        ratingText: "Good",
        isRecommendedAmount: false,
      },
      {
        rating: "😊",
        value: 18,
        ratingText: "Great",
        isRecommendedAmount: true,
      },
      {
        rating: "🤩",
        value: 20,
        ratingText: "Excellent",
        isRecommendedAmount: false,
      },
    ],
    id: 2,
    transKey: "sit-down-restaurant",
  },
  {
    category: "Food service",
    label: "Coffee shop",
    unit: "dollar",
    items: [
      {
        rating: "🙂",
        value: 1,
        ratingText: "Good",
        isRecommendedAmount: false,
      },
      {
        rating: "😊",
        value: 1.5,
        ratingText: "Great",
        isRecommendedAmount: true,
      },
      {
        rating: "🤩",
        value: 2,
        ratingText: "Excellent",
        isRecommendedAmount: false,
      },
    ],
    id: 3,
    transKey: "coffee-shop",
  },
  {
    category: "Food service",
    label: "Delivery",
    unit: "percentage",
    items: [
      {
        rating: "🙂",
        value: 10,
        ratingText: "Good",
        isRecommendedAmount: false,
      },
      {
        rating: "😊",
        value: 12,
        ratingText: "Great",
        isRecommendedAmount: true,
      },
      {
        rating: "🤩",
        value: 15,
        ratingText: "Excellent",
        isRecommendedAmount: false,
      },
    ],
    id: 4,
    transKey: "delivery",
  },
  {
    category: "Food service",
    label: "Bartender",
    unit: "dollar",
    note: "per drink",
    items: [
      {
        rating: "🙂",
        value: 1,
        ratingText: "Good",
        isRecommendedAmount: false,
      },
      {
        rating: "😊",
        value: 1.5,
        ratingText: "Great",
        isRecommendedAmount: true,
      },
      {
        rating: "🤩",
        value: 2,
        ratingText: "Excellent",
        isRecommendedAmount: false,
      },
    ],
    id: 5,
    transKey: "bartender",
  },
  {
    category: "Personal care",
    label: "Haircut",
    unit: "percentage",
    items: [
      {
        rating: "🙂",
        value: 15,
        ratingText: "Good",
        isRecommendedAmount: true,
      },
      {
        rating: "😊",
        value: 18,
        ratingText: "Great",
        isRecommendedAmount: false,
      },
      {
        rating: "🤩",
        value: 20,
        ratingText: "Excellent",
        isRecommendedAmount: false,
      },
    ],
    id: 6,
    transKey: "haircut",
  },
  {
    category: "Personal care",
    label: "Manicure/pedicure",
    unit: "percentage",
    items: [
      {
        rating: "🙂",
        value: 15,
        ratingText: "Good",
        isRecommendedAmount: false,
      },
      {
        rating: "😊",
        value: 18,
        ratingText: "Great",
        isRecommendedAmount: true,
      },
      {
        rating: "🤩",
        value: 20,
        ratingText: "Excellent",
        isRecommendedAmount: false,
      },
    ],
    id: 7,
    transKey: "manicure/pedicure",
  },
  {
    category: "Personal care",
    label: "Massage",
    unit: "percentage",
    items: [
      {
        rating: "🙂",
        value: 15,
        ratingText: "Good",
        isRecommendedAmount: false,
      },
      {
        rating: "😊",
        value: 18,
        ratingText: "Great",
        isRecommendedAmount: true,
      },
      {
        rating: "🤩",
        value: 20,
        ratingText: "Excellent",
        isRecommendedAmount: false,
      },
    ],
    id: 8,
    transKey: "massage",
  },
  {
    category: "Transportation",
    label: "Taxi",
    unit: "percentage",
    items: [
      {
        rating: "🙂",
        value: 10,
        ratingText: "Good",
        isRecommendedAmount: false,
      },
      {
        rating: "😊",
        value: 12,
        ratingText: "Great",
        isRecommendedAmount: true,
      },
      {
        rating: "🤩",
        value: 15,
        ratingText: "Excellent",
        isRecommendedAmount: false,
      },
    ],
    id: 9,
    transKey: "taxi",
  },
  {
    category: "Hotel",
    label: "Bellhop",
    unit: "dollar",
    note: "per bag",
    items: [
      {
        rating: "🙂",
        value: 1,
        ratingText: "Good",
        isRecommendedAmount: false,
      },
      {
        rating: "😊",
        value: 1.5,
        ratingText: "Great",
        isRecommendedAmount: true,
      },
      {
        rating: "🤩",
        value: 2,
        ratingText: "Excellent",
        isRecommendedAmount: false,
      },
    ],
    id: 10,
    transKey: "bellhop",
  },
  {
    category: "Hotel",
    label: "Housekeeping",
    unit: "dollar",
    note: "per night",
    items: [
      {
        rating: "🙂",
        value: 2,
        ratingText: "Good",
        isRecommendedAmount: false,
      },
      {
        rating: "😊",
        value: 3.5,
        ratingText: "Great",
        isRecommendedAmount: true,
      },
      {
        rating: "🤩",
        value: 5,
        ratingText: "Excellent",
        isRecommendedAmount: false,
      },
    ],
    id: 11,
    transKey: "housekeeping",
  },
  {
    category: "Miscellaneous",
    label: "Coat check",
    unit: "dollar",
    items: [
      {
        rating: "🙂",
        value: 1,
        ratingText: "Good",
        isRecommendedAmount: false,
      },
      {
        rating: "😊",
        value: 1.5,
        ratingText: "Great",
        isRecommendedAmount: true,
      },
      {
        rating: "🤩",
        value: 2,
        ratingText: "Excellent",
        isRecommendedAmount: false,
      },
    ],
    id: 12,
    transKey: "coat-check",
  },
  {
    category: "Miscellaneous",
    label: "Musician",
    unit: "dollar",
    items: [
      {
        rating: "🙂",
        value: 1,
        ratingText: "Good",
        isRecommendedAmount: false,
      },
      {
        rating: "😊",
        value: 3.5,
        ratingText: "Great",
        isRecommendedAmount: true,
      },
      {
        rating: "🤩",
        value: 5,
        ratingText: "Excellent",
        isRecommendedAmount: false,
      },
    ],
    id: 13,
    transKey: "musician",
  },
  {
    category: "Miscellaneous",
    label: "Valet",
    unit: "dollar",
    items: [
      {
        rating: "🙂",
        value: 2,
        ratingText: "Good",
        isRecommendedAmount: false,
      },
      {
        rating: "😊",
        value: 3.5,
        ratingText: "Great",
        isRecommendedAmount: true,
      },
      {
        rating: "🤩",
        value: 5,
        ratingText: "Excellent",
        isRecommendedAmount: false,
      },
    ],
    id: 14,
    transKey: "valet",
  },
];
